SET(CMAKE_C_COMPILER clang)
SET(CMAKE_CXX_COMPILER clang++)

# macOS 11 Big Sur is the first version to support ARM-based macs
SET(CMAKE_OSX_DEPLOYMENT_TARGET 11.0)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
