version: "3"
services:
 web:
  build: .
  ports:
   - '4567:4567'
  networks:
   - external_network
   - internal_network
  depends_on:
   - mysql
  volumes:
   - ./config.properties:/usr/local/etc/config.properties
   - /var/www/smithereen/s:/var/www/smithereen/s
  restart: always
 mysql:
  image: mysql:8
  environment:
   MYSQL_ROOT_PASSWORD: smithereen
   MYSQL_DATABASE: smithereen
   MYSQL_INITDB_SKIP_TZINFO: 1
  networks:
   - internal_network
  healthcheck:
   test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  volumes:
   - smithereen-mysql-data:/var/lib/mysql
   - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  restart: always
 imgproxy:
  image: darthsim/imgproxy:latest
  ports:
   - '4560:8080'
  environment:
   IMGPROXY_PATH_PREFIX: "/i"
   IMGPROXY_ALLOWED_SOURCES: "local://"
   IMGPROXY_LOCAL_FILESYSTEM_ROOT: "/var/www/smithereen/s"
   # See README or config_docker.properties for how to generate these.
   # Must match config, otherwise you won't be seeing any memes in the newsfeed.
   IMGPROXY_KEY: GENERATE YOUR OWN
   IMGPROXY_SALT: GENERATE YOUR OWN
  volumes:
   - /var/www/smithereen/s:/var/www/smithereen/s
  restart: always
  networks:
   - external_network

networks:
  external_network:
  internal_network:
    internal: true

volumes:
  smithereen-mysql-data:
