package smithereen.storage.sql;

import java.io.Closeable;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseConnection implements Closeable{
	public final Connection actualConnection;
	long lastUsed=System.nanoTime();
	int useDepth=0;
	Thread ownerThread;

	public DatabaseConnection(Connection actualConnection){
		this.actualConnection=actualConnection;
	}

	@Override
	public void close(){
		DatabaseConnectionManager.reuseConnection(this);
	}

	public PreparedStatement prepareStatement(String sql) throws SQLException{
		return actualConnection.prepareStatement(sql);
	}

	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException{
		return actualConnection.prepareStatement(sql, autoGeneratedKeys);
	}

	public Statement createStatement() throws SQLException{
		return actualConnection.createStatement();
	}
}
