package smithereen.storage.sql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import smithereen.Config;

public class DebugDatabaseConnection extends DatabaseConnection{
	Throwable throwableForStack;

	public DebugDatabaseConnection(Connection actualConnection){
		super(actualConnection);
	}

	@Override
	public PreparedStatement prepareStatement(String sql) throws SQLException{
		return Config.DEBUG ? new DebugPreparedStatement(super.prepareStatement(sql)) : super.prepareStatement(sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException{
		return Config.DEBUG ? new DebugPreparedStatement(super.prepareStatement(sql, autoGeneratedKeys)) : super.prepareStatement(sql, autoGeneratedKeys);
	}

	@Override
	public Statement createStatement() throws SQLException{
		return Config.DEBUG ? new DebugStatement(super.createStatement()) : super.createStatement();
	}
}
