SET(CMAKE_C_COMPILER clang)
SET(CMAKE_CXX_COMPILER clang++)

# Earliest supported version of macOS
SET(CMAKE_OSX_DEPLOYMENT_TARGET 10.15)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
