package smithereen.model.apps;

public enum ClientAppPermission{
	PASSWORD_GRANT_USED,
	FRIENDS_READ,
	FRIENDS_WRITE,
	PHOTOS_READ,
	PHOTOS_WRITE,
	ACCOUNT_WRITE,
	WALL_READ,
	WALL_WRITE,
	GROUPS_READ,
	GROUPS_WRITE,
	MESSAGES_READ,
	MESSAGES_WRITE,
	LIKES_READ,
	LIKES_WRITE,
	NEWSFEED,
	NOTIFICATIONS,
	OFFLINE
}
